export const INITIAL_PROJECTS = [
  {
    id: 1,
    name: 'Piso Carrer Paris',
    description:
      'Gestión integral del piso en Carrer Paris: reforma, alquiler, documentación y seguimiento financiero.',
    status: 'Activo',
    priority: 'Alta',
    startDate: '2024-01-15',
    deadline: '2024-12-31',
    color: '#1D9E75',
    transactions: [
      { id: 1, type: 'ingreso', concept: 'Depósito de fianza', amount: 2400, date: '2024-01-20', category: 'Alquiler', comment: 'Fianza inicial del inquilino' },
      { id: 2, type: 'ingreso', concept: 'Alquiler enero', amount: 1200, date: '2024-01-31', category: 'Alquiler', comment: '' },
      { id: 3, type: 'ingreso', concept: 'Alquiler febrero', amount: 1200, date: '2024-02-28', category: 'Alquiler', comment: '' },
      { id: 4, type: 'gasto', concept: 'Reforma baño', amount: 3500, date: '2024-02-10', category: 'Reforma', comment: 'Azulejos y sanitarios nuevos' },
      { id: 5, type: 'gasto', concept: 'Comunidad enero', amount: 85, date: '2024-01-05', category: 'Comunidad', comment: '' },
      { id: 6, type: 'gasto', concept: 'IBI anual', amount: 420, date: '2024-03-01', category: 'Impuestos', comment: 'Impuesto bienes inmuebles' },
      { id: 7, type: 'ingreso', concept: 'Alquiler marzo', amount: 1200, date: '2024-03-31', category: 'Alquiler', comment: '' },
    ],
    tasks: [
      { id: 1, title: 'Renovar contrato de alquiler', description: 'El contrato vence en diciembre, preparar renovación', status: 'Pendiente', priority: 'Alta', deadline: '2024-11-30' },
      { id: 2, title: 'Certificado energético', description: 'Obtener certificado para renovar alquiler', status: 'Completada', priority: 'Media', deadline: '2024-03-15' },
      { id: 3, title: 'Revisión fontanería', description: 'Revisar tuberías cocina por posible humedad', status: 'En progreso', priority: 'Alta', deadline: '2024-04-30' },
      { id: 4, title: 'Declaración renta alquiler', description: 'Incluir ingresos del alquiler en la declaración', status: 'Pendiente', priority: 'Media', deadline: '2024-06-30' },
      { id: 5, title: 'Pintar salón', description: 'El inquilino ha pedido repintar el salón', status: 'Completada', priority: 'Baja', deadline: '2024-02-28' },
    ],
    comments: [
      { id: 1, text: 'El inquilino confirma que todo está en orden. Muy buen pagador.', date: '2024-03-01', tag: 'Avance' },
      { id: 2, text: 'Pendiente revisar si la calefacción necesita mantenimiento antes del invierno.', date: '2024-03-15', tag: 'Recordatorio' },
      { id: 3, text: 'Decidido actualizar el precio del alquiler un 3% en la renovación.', date: '2024-03-20', tag: 'Decisión' },
    ],
    files: [
      { id: 1, name: 'Contrato_alquiler_2024.pdf', type: 'PDF', date: '2024-01-15', comment: 'Contrato firmado' },
      { id: 2, name: 'Presupuesto_reforma_bano.pdf', type: 'PDF', date: '2024-02-05', comment: 'Presupuesto aceptado' },
    ],
    manualProgress: null,
  },
  {
    id: 2,
    name: 'Proyecto 2',
    description: 'Descripción del proyecto 2. Edita este texto para personalizarlo.',
    status: 'Activo',
    priority: 'Media',
    startDate: '2024-02-01',
    deadline: '2024-09-30',
    color: '#378ADD',
    transactions: [
      { id: 1, type: 'ingreso', concept: 'Venta servicio A', amount: 5000, date: '2024-02-15', category: 'Ventas', comment: '' },
      { id: 2, type: 'gasto', concept: 'Marketing digital', amount: 800, date: '2024-02-20', category: 'Marketing', comment: '' },
    ],
    tasks: [
      { id: 1, title: 'Definir alcance del proyecto', description: '', status: 'Completada', priority: 'Alta', deadline: '2024-02-15' },
      { id: 2, title: 'Reunión con cliente', description: '', status: 'Completada', priority: 'Alta', deadline: '2024-03-01' },
      { id: 3, title: 'Entrega primera fase', description: '', status: 'En progreso', priority: 'Media', deadline: '2024-05-01' },
    ],
    comments: [{ id: 1, text: 'Proyecto arrancado. Buen comienzo.', date: '2024-02-01', tag: 'Avance' }],
    files: [],
    manualProgress: null,
  },
  {
    id: 3,
    name: 'Proyecto 3',
    description: 'Descripción del proyecto 3. Edita este texto para personalizarlo.',
    status: 'Pausado',
    priority: 'Baja',
    startDate: '2024-01-10',
    deadline: '2024-08-31',
    color: '#D85A30',
    transactions: [
      { id: 1, type: 'gasto', concept: 'Materiales', amount: 1200, date: '2024-01-15', category: 'Materiales', comment: '' },
    ],
    tasks: [
      { id: 1, title: 'Investigación de mercado', description: '', status: 'Completada', priority: 'Media', deadline: '2024-02-01' },
      { id: 2, title: 'Prototipo inicial', description: '', status: 'Pendiente', priority: 'Alta', deadline: '2024-06-30' },
    ],
    comments: [],
    files: [],
    manualProgress: null,
  },
  {
    id: 4,
    name: 'Proyecto 4',
    description: 'Descripción del proyecto 4. Edita este texto para personalizarlo.',
    status: 'Urgente',
    priority: 'Alta',
    startDate: '2024-03-01',
    deadline: '2024-04-30',
    color: '#E24B4A',
    transactions: [
      { id: 1, type: 'ingreso', concept: 'Anticipo cliente', amount: 3000, date: '2024-03-05', category: 'Ventas', comment: '' },
      { id: 2, type: 'gasto', concept: 'Horas consultoría', amount: 1500, date: '2024-03-10', category: 'Servicios', comment: '' },
    ],
    tasks: [
      { id: 1, title: 'Entrega urgente documentación', description: '', status: 'En progreso', priority: 'Alta', deadline: '2024-04-10' },
      { id: 2, title: 'Revisión legal', description: '', status: 'Pendiente', priority: 'Alta', deadline: '2024-04-20' },
      { id: 3, title: 'Firma contrato', description: '', status: 'Pendiente', priority: 'Alta', deadline: '2024-04-30' },
    ],
    comments: [{ id: 1, text: 'Hay que acelerar este proyecto. Fecha límite crítica.', date: '2024-03-15', tag: 'Problema' }],
    files: [],
    manualProgress: null,
  },
  {
    id: 5,
    name: 'Proyecto 5',
    description: 'Descripción del proyecto 5. Edita este texto para personalizarlo.',
    status: 'Finalizado',
    priority: 'Media',
    startDate: '2023-10-01',
    deadline: '2024-01-31',
    color: '#7F77DD',
    transactions: [
      { id: 1, type: 'ingreso', concept: 'Factura final', amount: 8000, date: '2024-01-25', category: 'Ventas', comment: '' },
      { id: 2, type: 'gasto', concept: 'Subcontrata', amount: 2000, date: '2023-12-01', category: 'Servicios', comment: '' },
    ],
    tasks: [
      { id: 1, title: 'Planificación', description: '', status: 'Completada', priority: 'Alta', deadline: '2023-10-15' },
      { id: 2, title: 'Desarrollo', description: '', status: 'Completada', priority: 'Alta', deadline: '2023-12-31' },
      { id: 3, title: 'Entrega final', description: '', status: 'Completada', priority: 'Alta', deadline: '2024-01-31' },
    ],
    comments: [{ id: 1, text: 'Proyecto completado con éxito. Cliente muy satisfecho.', date: '2024-01-31', tag: 'Avance' }],
    files: [{ id: 1, name: 'Informe_final.pdf', type: 'PDF', date: '2024-01-31', comment: 'Entrega definitiva' }],
    manualProgress: null,
  },
  {
    id: 6,
    name: 'Proyecto 6',
    description: 'Descripción del proyecto 6. Edita este texto para personalizarlo.',
    status: 'Activo',
    priority: 'Media',
    startDate: '2024-03-15',
    deadline: '2024-10-31',
    color: '#BA7517',
    transactions: [],
    tasks: [
      { id: 1, title: 'Kick-off del proyecto', description: '', status: 'Completada', priority: 'Alta', deadline: '2024-03-20' },
      { id: 2, title: 'Fase de análisis', description: '', status: 'En progreso', priority: 'Media', deadline: '2024-04-30' },
    ],
    comments: [],
    files: [],
    manualProgress: null,
  },
];
